export const navItems = [
    { name: "About", link: "#about" },
    { name: "Projects", link: "#projects" },
    { name: "Experience", link: "#experience"},
    { name: "Contact", link: "#contact" },
  ];
  
  export const gridItems = [
    {
      id: 1,
      title: "I'm from the Beautiful British Columbia",
      description: "",
      className: "col-span-1 row-span-2 lg:col-span-3 md:col-span-6 md:row-span-4 text-white sm:min-h-[500px] sm:max-h-[600px]",
      imgClassName: "w-full",
      titleClassName: "justify-end mt-2",
      img: "/bc.png",
      spareImg: "",
    },
    {
      id: 2,
      title: "The bay's tech scene drew me here",
      description: "",
      className: "row-span-4 lg:col-span-2 md:col-span-3 md:row-span-2 sm:min-h-[225px] sm:max-h-[275px]",
      imgClassName: "",
      titleClassName: "justify-start -mt-4",
      img: "",
      spareImg: "",
    },
    {
      id: 3,
      title: "I study at the University of San Francisco",
      description: "",
      className: "lg:col-span-2 md:col-span-3 md:row-span-2",
      imgClassName: "",
      titleClassName: "justify-start -mt-4",
      img: "",
      spareImg: "",
    },
    {
      id: 4,
      title: "Fun fact: I also love to program games",
      description: "",
      className: "lg:col-span-2 md:col-span-3 md:row-span-1  ",
      imgClassName: "",
      titleClassName: "justify-end",
      img: "/grid.svg",
      spareImg: "/virusImage.png",
    },
  
    {
      id: 5,
      title: "Building an e-commerce website for my sister's jewlery startup brand (coming soon)",
      description: "What I Am Working On Currently",
      className: "md:col-span-3 md:row-span-2 hidden sm:block",
      imgClassName: "absolute right-0 bottom-0 md:w-96 w-60 ",
      titleClassName: "justify-center md:justify-start lg:justify-center -mt-20",
      img: "/b5.svg",
      spareImg: "/grid.svg",
    },
    {
      id: 6,
      title: "Can I work with you to create your next project?",
      description: "",
      className: "lg:col-span-2 md:col-span-3 md:row-span-1 text-white",
      imgClassName: "",
      titleClassName: "justify-center md:max-w-full max-w-60 text-center lg:-mt-2",
      img: "",
      spareImg: "",
    },
  ];

  export const techStack = [
    {
      id: 1,
      name: "React.js",
      image: "/re.svg",
    },
    {
      id: 2,
      name: "Next.js",
      image: "/next.svg",
    },
    {
      id: 3,
      name: "TypeScript",
      image: "/ts.svg",
    },
    {
      id: 4,
      name: "Javascript",
      image: "/javascript.svg",
    }, 
    {
      id: 5,
      name: "Java",
      image: "/java.svg",
    }, 
    {
      id: 6,
      name: "C",
      image: "/cLanguage.svg",
    }, 
    {
      id: 7,
      name: "Tailwind CSS",
      image: "/tail.svg",
    },
    {
      id: 9,
      name: "OpenAI API",
      image: "/openai.svg",
    }, 
    {
      id: 11,
      name: "Processing 4",
      image: "/Processing.svg",
    }, 
    {
      id: 12,
      name: "Google Cloud",
      image: "/google.svg",
    }, 
    {
      id: 13,
      name: "MongoDB",
      image: "/mongo.svg",
    }, 
  ]
  
  export const projects = [
    {
      id: 1,
      title: "Podify: AI Generated Podcasts",
      des: "Create, share and listen to podcasts generated by AI!",
      img: "/podify.png",
      iconLists: ["/next.svg", "/openai.svg", "/convexlogo.png", "/clerklogo.avif",  "/tail.svg", "/shadcnlogo.png" ],
      link: "https://podify-rfu3yqwfh-dd-dengs-projects.vercel.app/",
    },
    {
      id: 2,
      title: "Prompt-A-Chat: AI Prompt Sharing APP",
      des: "Discover & Share useful prompts to use for ChatGPT.",
      img: "/Prompt-A-Chat_LandingPage.png",
      iconLists: ["/next.svg", "nextauth.png", "/mongo.svg", "/tail.svg"],
      link: "https://prompt-a-chat-h5ynvd9ht-dd-dengs-projects.vercel.app",
    },
    {
      id: 3,
      title: "Dungeon Crawler RPG",
      des: "Explore through procedurally generated dungeon levels",
      img: "/RpgProjectScreenshot.png",
      iconLists: ["/Processing.svg", "/java.svg"],
      link: "https://www.youtube.com/watch?v=dQJ5l9eZSww",
    },
    {
      id: 4,
      title: "Pong Clone",
      des: "A pong remake that features 1 or 2 player modes.",
      img: "/PongScreenshot.png",
      iconLists: ["/Processing.svg", "/java.svg"],
      link: "https://www.youtube.com/watch?v=EbVVpmaXPzI",
    },
    
  ];
  
  export const testimonials = [
    {
      quote:
        "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
      name: "Michael Johnson",
      title: "Director of AlphaStream Technologies",
    },
    {
      quote:
        "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
      name: "Michael Johnson",
      title: "Director of AlphaStream Technologies",
    },
    {
      quote:
        "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
      name: "Michael Johnson",
      title: "Director of AlphaStream Technologies",
    },
    {
      quote:
        "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
      name: "Michael Johnson",
      title: "Director of AlphaStream Technologies",
    },
    {
      quote:
        "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
      name: "Michael Johnson",
      title: "Director of AlphaStream Technologies",
    },
  ];
  
  export const companies = [
    {
      id: 1,
      name: "cloudinary",
      img: "/cloud.svg",
      nameImg: "/cloudName.svg",
    },
    {
      id: 2,
      name: "appwrite",
      img: "/app.svg",
      nameImg: "/appName.svg",
    },
    {
      id: 3,
      name: "HOSTINGER",
      img: "/host.svg",
      nameImg: "/hostName.svg",
    },
    {
      id: 4,
      name: "stream",
      img: "/s.svg",
      nameImg: "/streamName.svg",
    },
    {
      id: 5,
      name: "docker.",
      img: "/dock.svg",
      nameImg: "/dockerName.svg",
    },
  ];
  
  export const workExperience = [
    {
      id: 1,
      title: "Frontend Engineer Intern (bookalift.com)",
      desc: "Optimized and redesigned website layout and updated web content leading to a 17% increase in conversion rate",
      className: "md:col-span-2",
      thumbnail: "/escalade.png",
      link: "https://bookalift.com"
    },
    {
      id: 2,
      title: "Web Developer at Lord Byng E-Sports Club",
      desc: "Designed and implemented a blog website for our school's E-Sports club, documenting our 50+ competitive games played in the 2023 season and our jouney to become provincial champtions",
      className: "md:col-span-2",
      thumbnail: "/league.png",
      link: "https://youtu.be/viXTQBibaEU"
    },
    {
      id: 3,
      title: "English Tutor at the GUM Learning Non-Profit Organization",
      desc: "Using my bilingual advantage to teach English to kids from rural China, helping bridge cultural gaps worldwide",
      classname: "md:col-span-2",
      thumbnail: "/tutor.png",
      link: "https://docs.google.com/document/d/1710ASmqssZ0uj2w7W87IFjIBNMo1Arl4hoPdudtGFh0/edit",
    },
  ];
  
  export const socialMedia = [
    {
      id: 1,
      img: "/git.svg",
      url: "https://github.com/ddssamu3l",
    },
    {
      id: 2,
      img: "/link.svg",
      url: "https://www.linkedin.com/in/jingxi-deng-6b2b37307/"
    },
    {
      id: 3,
      img: "/YouTube.svg",
      url: "https://www.youtube.com/channel/UCrSxSS-B8hw6vMmy___7zLQ"
    },
  ];

  export const cards = [
    {
      description: "Lana Del Rey",
      title: "Summertime Sadness",
      src: "https://assets.aceternity.com/demos/lana-del-rey.jpeg",
      ctaText: "Visit",
      ctaLink: "https://ui.aceternity.com/templates",
      content: () => {
        return (
          <p>
            Lana Del Rey, an iconic American singer-songwriter, is celebrated for
            her melancholic and cinematic music style. Born Elizabeth Woolridge
            Grant in New York City, she has captivated audiences worldwide with
            her haunting voice and introspective lyrics. <br /> <br /> Her songs
            often explore themes of tragic romance, glamour, and melancholia,
            drawing inspiration from both contemporary and vintage pop culture.
            With a career that has seen numerous critically acclaimed albums, Lana
            Del Rey has established herself as a unique and influential figure in
            the music industry, earning a dedicated fan base and numerous
            accolades.
          </p>
        );
      },
    },
    {
      description: "Babbu Maan",
      title: "Mitran Di Chhatri",
      src: "https://assets.aceternity.com/demos/babbu-maan.jpeg",
      ctaText: "Visit",
      ctaLink: "https://ui.aceternity.com/templates",
      content: () => {
        return (
          <p>
            Babu Maan, a legendary Punjabi singer, is renowned for his soulful
            voice and profound lyrics that resonate deeply with his audience. Born
            in the village of Khant Maanpur in Punjab, India, he has become a
            cultural icon in the Punjabi music industry. <br /> <br /> His songs
            often reflect the struggles and triumphs of everyday life, capturing
            the essence of Punjabi culture and traditions. With a career spanning
            over two decades, Babu Maan has released numerous hit albums and
            singles that have garnered him a massive fan following both in India
            and abroad.
          </p>
        );
      },
    },
  
    {
      description: "Metallica",
      title: "For Whom The Bell Tolls",
      src: "https://assets.aceternity.com/demos/metallica.jpeg",
      ctaText: "Visit",
      ctaLink: "https://ui.aceternity.com/templates",
      content: () => {
        return (
          <p>
            Metallica, an iconic American heavy metal band, is renowned for their
            powerful sound and intense performances that resonate deeply with
            their audience. Formed in Los Angeles, California, they have become a
            cultural icon in the heavy metal music industry. <br /> <br /> Their
            songs often reflect themes of aggression, social issues, and personal
            struggles, capturing the essence of the heavy metal genre. With a
            career spanning over four decades, Metallica has released numerous hit
            albums and singles that have garnered them a massive fan following
            both in the United States and abroad.
          </p>
        );
      },
    },
    {
      description: "Lord Himesh",
      title: "Aap Ka Suroor",
      src: "https://assets.aceternity.com/demos/aap-ka-suroor.jpeg",
      ctaText: "Visit",
      ctaLink: "https://ui.aceternity.com/templates",
      content: () => {
        return (
          <p>
            Himesh Reshammiya, a renowned Indian music composer, singer, and
            actor, is celebrated for his distinctive voice and innovative
            compositions. Born in Mumbai, India, he has become a prominent figure
            in the Bollywood music industry. <br /> <br /> His songs often feature
            a blend of contemporary and traditional Indian music, capturing the
            essence of modern Bollywood soundtracks. With a career spanning over
            two decades, Himesh Reshammiya has released numerous hit albums and
            singles that have garnered him a massive fan following both in India
            and abroad.
          </p>
        );
      },
    },
  ];
  