export const navItems = [
    { name: "About", link: "#about" },
    { name: "Projects", link: "#projects" },
    { name: "Experience", link: "#experience"},
    { name: "Contact", link: "#contact" },
  ];
  
  export const gridItems = [
    {
      id: 1,
      title: "I'm from the Beautiful British Columbia",
      description: "",
      className: "col-span-1 row-span-2 lg:col-span-3 md:col-span-6 md:row-span-4 text-white sm:min-h-[500px] sm:max-h-[600px]",
      imgClassName: "w-full",
      titleClassName: "justify-end mt-2",
      img: "/bc.png",
      spareImg: "",
    },
    {
      id: 2,
      title: "The bay's tech scene drew me here",
      description: "",
      className: "row-span-4 lg:col-span-2 md:col-span-3 md:row-span-2 sm:min-h-[225px] sm:max-h-[275px]",
      imgClassName: "",
      titleClassName: "justify-start -mt-4",
      img: "",
      spareImg: "",
    },
    {
      id: 3,
      title: "I study at the University of San Francisco",
      description: "",
      className: "lg:col-span-2 md:col-span-3 md:row-span-2",
      imgClassName: "",
      titleClassName: "justify-start -mt-4",
      img: "",
      spareImg: "",
    },
    {
      id: 4,
      title: "Fun fact: I also love to program games",
      description: "",
      className: "lg:col-span-2 md:col-span-3 md:row-span-1  ",
      imgClassName: "",
      titleClassName: "justify-end",
      img: "/grid.svg",
      spareImg: "/virusImage.png",
    },
  
    {
      id: 5,
      title: "Building an e-commerce website for my sister's jewlery startup brand (coming soon)",
      description: "What I Am Working On Currently",
      className: "md:col-span-3 md:row-span-2 hidden sm:block",
      imgClassName: "absolute right-0 bottom-0 md:w-96 w-60 ",
      titleClassName: "justify-center md:justify-start lg:justify-center -mt-20",
      img: "/b5.svg",
      spareImg: "/grid.svg",
    },
    {
      id: 6,
      title: "Can I work with you to create your next project?",
      description: "",
      className: "lg:col-span-2 md:col-span-3 md:row-span-1 text-white",
      imgClassName: "",
      titleClassName: "justify-center md:max-w-full max-w-60 text-center lg:-mt-2",
      img: "",
      spareImg: "",
    },
  ];

  export const techStack = [
    {
      id: 1,
      name: "React.js",
      image: "/re.svg",
    },
    {
      id: 2,
      name: "Next.js",
      image: "/next.svg",
    },
    {
      id: 3,
      name: "TypeScript",
      image: "/ts.svg",
    },
    {
      id: 4,
      name: "Javascript",
      image: "/javascript.svg",
    }, 
    {
      id: 5,
      name: "Java",
      image: "/java.svg",
    }, 
    {
      id: 6,
      name: "C",
      image: "/cLanguage.svg",
    }, 
    {
      id: 15,
      name: "Go",
      image: "/Go.svg",
    },
    {
      id: 7,
      name: "Tailwind CSS",
      image: "/tail.svg",
    },
    {
      id: 9,
      name: "OpenAI API",
      image: "/openai.svg",
    }, 
    {
      id: 11,
      name: "Processing 4",
      image: "/Processing.svg",
    }, 
    {
      id: 12,
      name: "Google Cloud",
      image: "/google.svg",
    }, 
    {
      id: 13,
      name: "MongoDB",
      image: "/mongo.svg",
    }, 
    {
      id: 14,
      name: "Vercel",
      image: "/vercel.svg",
    }, 
    {
      id: 15,
      name: "Three.js",
      image: "/three.svg",
    }, 
  ]
  
  export const projects = [
    {
      id: 1,
      title: "Podify: AI Generated Podcasts",
      des: "Create, share and listen to podcasts generated by AI!",
      img: "/podify.png",
      iconLists: ["/next.svg", "/openai.svg", "/vercel.svg", "/convexlogo.png", "/clerklogo.avif",  "/tail.svg", "/shadcnlogo.png" ],
      link: "https://podify-rfu3yqwfh-dd-dengs-projects.vercel.app/",
    },
    {
      id: 2,
      title: "Prompt-A-Chat: AI Prompt Sharing APP",
      des: "Discover & Share useful prompts to use for ChatGPT.",
      img: "/Prompt-A-Chat_LandingPage.png",
      iconLists: ["/next.svg", "nextauth.png", "/vercel.svg", "/mongo.svg", "/tail.svg"],
      link: "https://prompt-a-chat-h5ynvd9ht-dd-dengs-projects.vercel.app",
    },
    {
      id: 3,
      title: "Dungeon Crawler RPG",
      des: "Explore through procedurally generated dungeon levels",
      img: "/RpgProjectScreenshot.png",
      iconLists: ["/Processing.svg", "/java.svg"],
      link: "https://www.youtube.com/watch?v=dQJ5l9eZSww",
    },
    {
      id: 4,
      title: "Pong Clone",
      des: "A pong remake that features 1 or 2 player modes.",
      img: "/PongScreenshot.png",
      iconLists: ["/Processing.svg", "/java.svg"],
      link: "https://www.youtube.com/watch?v=EbVVpmaXPzI",
    },
    
  ];
  
  export const testimonials = [
    {
      quote:
        "I really want to thank Samuel who has paid great attention, patience and efforts in both designing and teaching my little girl Alice during the whole course.",
      name: "Alice's parents",
      title: "Student at GUM Learning Organization",
    },
    {
      quote:
        "Jingxi's professional communication skills exceed his junior title. His ideas and propersals easily understood and vocabulary use is efficient. He has been a pleasure to work with.",
      name: "Graham Macdougall",
      title: "Founder and owner of Bookalift",
    },
    {
      quote:
        "Samuel's leadership skills was crucial to our victory at the provincial champtionship. He is soneone who stays calm under pressure and kept our team organized.",
      name: "Kris Zhao",
      title: "Jungler at Lord Byng E-Sports Club",
    },
  ];
  
  export const workExperience = [
    {
      id: 2,
      title: "Computer Science Mentor - USF Mentorship Collective Program",
      desc: "Increasing overall mentee grades by 10% through conducting one-on-one and group mentoring sessions, helping 10+ students find academic success in Computer Science courses.",
      className: "md:col-span-2",
      thumbnail: "/usf_dons.svg",
    },
    {
      id: 2,
      title: "Full Stack Engineer Intern - bookalift.com",
      desc: "Optimized and redesigned website layout and updated web content leading to a 17% increase in conversion rate.",
      className: "md:col-span-2",
      thumbnail: "/escalade.png",
      link: "https://bookalift.com"
    },
    {
      id: 3,
      title: "Web Developer - Lord Byng E-Sports Club",
      desc: "Designed and implemented a blog website for our school's E-Sports club, documenting 50+ competitive games played in the 2023 season to become provincial champtions.",
      className: "md:col-span-2",
      thumbnail: "/league.png",
      link: "https://youtu.be/viXTQBibaEU"
    },
    {
      id: 4,
      title: "English Tutor - GUM Learning Non-Profit Organization",
      desc: "Using my bilingual advantage to teach English to kids from rural China, helping bridge cultural gaps worldwide.",
      classname: "md:col-span-2",
      thumbnail: "/tutor.png",
      link: "https://docs.google.com/document/d/1710ASmqssZ0uj2w7W87IFjIBNMo1Arl4hoPdudtGFh0/edit",
    },
  ];
  
  export const socialMedia = [
    {
      id: 1,
      img: "/git.svg",
      url: "https://github.com/ddssamu3l",
    },
    {
      id: 2,
      img: "/link.svg",
      url: "https://www.linkedin.com/in/jingxi-deng-6b2b37307/"
    },
    {
      id: 3,
      img: "/YouTube.svg",
      url: "https://www.youtube.com/channel/UCrSxSS-B8hw6vMmy___7zLQ"
    },
  ];

  