export const navItems = [
    { name: "About", link: "#about" },
    { name: "Projects", link: "#projects" },
    { name: "Experience", link: "#experience"},
    { name: "Contact", link: "#contact" },
  ];
  
  export const gridItems = [
    {
      id: 1,
      title: "I'm from the beautiful British Columbia",
      description: "",
      className: "col-span-1 row-span-2 lg:col-span-3 md:col-span-6 md:row-span-4 text-white sm:min-h-[500px] sm:max-h-[600px] aspect-[5/4] sm:aspect-auto",
      imgClassName: "w-full",
      titleClassName: "justify-end mt-4",
      img: "/bc.png",
      spareImg: "",
    },
    {
      id: 2,
      title: "The bay's tech scene drew me here",
      description: "",
      className: "row-span-4 lg:col-span-2 md:col-span-3 md:row-span-2 sm:min-h-[225px] sm:max-h-[275px]",
      imgClassName: "",
      titleClassName: "justify-start -mt-4",
      img: "",
      spareImg: "",
    },
    {
      id: 3,
      title: "I study at the University of San Francisco",
      description: "",
      className: "lg:col-span-2 md:col-span-3 md:row-span-2",
      imgClassName: "",
      titleClassName: "justify-start -mt-4",
      img: "",
      spareImg: "",
    },
    {
      id: 4,
      title: "Fun fact: I also love to program games",
      description: "",
      className: "lg:col-span-2 md:col-span-3 md:row-span-1  ",
      imgClassName: "",
      titleClassName: "justify-end",
      img: "/grid.svg",
      spareImg: "/virusImage.png",
    },
  
    {
      id: 5,
      title: "Building an e-commerce website for my sister's jewlery startup brand (coming soon)",
      description: "What I Am Working On Currently",
      className: "md:col-span-3 md:row-span-2 hidden sm:block",
      imgClassName: "absolute right-0 bottom-0 md:w-96 w-60 ",
      titleClassName: "justify-center md:justify-start lg:justify-center -mt-20",
      img: "/b5.svg",
      spareImg: "/grid.svg",
    },
    {
      id: 6,
      title: "Can I work with you to create your next project?",
      description: "",
      className: "lg:col-span-2 md:col-span-3 md:row-span-1 text-white",
      imgClassName: "",
      titleClassName: "justify-center md:max-w-full max-w-60 text-center lg:-mt-2",
      img: "",
      spareImg: "",
    },
  ];

  export const techStack = [
    {
      id: 1,
      name: "Java",
      image: "/java.svg",
    },
    {
      id: 2,
      name: "C",
      image: "/cLanguage.svg",
    },
    {
      id: 3,
      name: "Go",
      image: "/Go.svg",
    },
    {
      id: 4,
      name: "React.js",
      image: "/re.svg",
    },
    {
      id: 5,
      name: "Next.js",
      image: "/next.svg",
    },
    {
      id: 6,
      name: "TypeScript",
      image: "/ts.svg",
    },
    {
      id: 7,
      name: "Angluar",
      image: "/angular.svg",
    },
    {
      id: 8,
      name: "Javascript",
      image: "/javascript.svg",
    },
    {
      id: 9,
      name: "HTML",
      image: "/html.svg",
    },
    {
      id: 10,
      name: "CSS",
      image: "/css.svg",
    },
    {
      id: 11,
      name: "jQuery",
      image: "/jquery.svg",
    },
    {
      id: 12,
      name: "Handlebars",
      image: "/handlebars.svg",
    },
    {
      id: 13,
      name: "Tailwind CSS",
      image: "/tail.svg",
    },
    {
      id: 14,
      name: "AWS S3",
      image: "/s3.svg",
    },
    {
      id: 15,
      name: "AWS Lambda",
      image: "/lambda.svg",
    },
    {
      id: 16,
      name: "AWS Cognito",
      image: "/cognito.svg",
    },
    {
      id: 17,
      name: "Vs Code API",
      image: "/vscode.svg",
    },
    {
      id: 18,
      name: "OpenAI API",
      image: "/openai.svg",
    },
    {
      id: 19,
      name: "Google Cloud",
      image: "/google.svg",
    },
    {
      id: 20,
      name: "MongoDB",
      image: "/mongo.svg",
    },
    {
      id: 21,
      name: "Vercel",
      image: "/vercel.svg",
    },
    {
      id: 22,
      name: "Docker",
      image: "/docker.svg",
    },
    {
      id: 23,
      name: "Ollama",
      image: "/ollama.svg",
    },
  ];


  
  export const projects = [
    {
      id: 1,
      title: "DeepSeek R1 Vs Code Extension",
      des: "Chat interfce extension that runs DeepSeek R1 locally",
      img: "/deepseek-ext.webp",
      iconLists: ["/ts.svg", "/vscode.svg", "/ollama.svg"],
      link: "https://github.com/ddssamu3l/DeepSeekVsCodeExtension",
    },
    {
      id: 2,
      title: "RAG-Assisted AI ChatBot",
      des: "A course-selection helper agent that queries databases",
      img: "/chatbot.webp",
      iconLists: ["/go.svg", "/openai.svg"],
      link: "https://github.com/ddssamu3l/RAG_Chatbot",
    },
    {
      id: 3,
      title: "Podify: AI Generated Podcasts",
      des: "Create, share and listen to podcasts generated by AI!",
      img: "/podify.png",
      iconLists: ["/next.svg", "/openai.svg", "/vercel.svg", "/convexlogo.png", "/clerklogo.avif",  "/tail.svg", "/shadcnlogo.png" ],
      link: "https://github.com/ddssamu3l/Podify-AI_Saas_podcast",
    },
    {
      id: 4,
      title: "Prompt-A-Chat: AI Prompt Sharing APP",
      des: "Discover & Share useful prompts to use for ChatGPT.",
      img: "/Prompt-A-Chat_LandingPage.png",
      iconLists: ["/next.svg", "nextauth.png", "/vercel.svg", "/mongo.svg", "/tail.svg"],
      link: "https://github.com/ddssamu3l/prompt-a-chat",
    },
  ];
  
  export const testimonials = [
    {
      quote:
        "Samuel played a vital role in optimizing and enhancing our core applications, optimizing our AI agents, enabling us to maintain momentum and deliver projects on schedule.  ",
      name: "Serge Amouzou",
      title: "Founder and CEO of Datatrixs",
    },
    {
      quote:
        "Jingxi's professional communication skills exceed his junior title. His ideas and propersals easily understood and vocabulary use is efficient. He has been a pleasure to work with.",
      name: "Graham Macdougall",
      title: "Founder and owner of Bookalift",
    },
    {
      quote:
        "Samuel's leadership skills was crucial to our victory at the provincial champtionship. He is soneone who stays calm under pressure and kept our team organized.",
      name: "Kris Zhao",
      title: "Jungler at Lord Byng E-Sports Club",
    },
  ];
  
  export const workExperience = [
    {
      id: 1,
      title: "Software Engineer Intern - Datatrixs",
      desc: "Developed SSO features, optimized AI performance with AWS S3 and MongoDB, and helped Datatrixs go to market in the Intuit marketplace by meeting technical compliance standards.",
      className: "md:col-span-2",
      thumbnail: "/datatrixs.png",
    },
    {
      id: 2,
      title: "Computer Science Mentor - USF Mentorship Collective Program",
      desc: "Held private and group mentoring sessions on Data Structures & Algorithms, Object Oriented Programming, Linear Algebra and more. Assisted students in applying their CPT visas to secure their software internships.",
      className: "md:col-span-2",
      thumbnail: "/usf_dons.svg",
    },
    {
      id: 3,
      title: "Full Stack Engineer Intern - bookalift.com",
      desc: "Integrated Square Payment's APIs to allow for online checkout and redesigned bookalift.ca's frontend with Next.js.",
      className: "md:col-span-2",
      thumbnail: "/escalade.png",
      link: "https://bookalift.com"
    },
    {
      id: 4,
      title: "Web Developer - Lord Byng E-Sports Club",
      desc: "Designed and implemented a blog website for our school's E-Sports club, documenting 50+ competitive games played in the 2023 season to become provincial champtions.",
      className: "md:col-span-2",
      thumbnail: "/league.png",
      link: "https://youtu.be/viXTQBibaEU"
    },
  ];
  
  export const socialMedia = [
    {
      id: 1,
      img: "/git.svg",
      url: "https://github.com/ddssamu3l",
    },
    {
      id: 2,
      img: "/link.svg",
      url: "https://www.linkedin.com/in/jingxi-deng-6b2b37307/"
    },
    {
      id: 3,
      img: "/YouTube.svg",
      url: "https://www.youtube.com/channel/UCrSxSS-B8hw6vMmy___7zLQ"
    },
  ];

  